import BlogDetailBanner from "@/components/blogDetails/BlogDetailBanner";
import BlogDetails from "@/components/blogDetails/BlogDetails";
import Head from "next/head";
import { blogs } from "@/data/blog";
import Blog from "@/components/shared/blog/Blog";

const BlogDetailsPage = ({singleBlog}) => {

  return (
    <>
      <Head>
        <title>Job Portal | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogDetailBanner/>
      <BlogDetails singleBlog={singleBlog}/>
      <Blog dataClass="blog-details-blog"/>
    </>
  )
}

export default BlogDetailsPage;

export const getStaticProps = async ({params}) => {
  const data = blogs.find(({id}) => id === params.blogId);

  return{
    props: {
      singleBlog: data
    }
  }
}

export const getStaticPaths = async () => {
  const paths = blogs.map((blog) => {
    return {
      params: {
        blogId: blog.id
      }
    }
  })

  return {paths, fallback: false}
}