import AllBlogs from "@/components/blogPage/AllBlogs"
import BlogBanner from "@/components/blogPage/BlogBanner"
import FeaturedBlog from "@/components/blogPage/featuredBlog/FeaturedBlog"
import Newsletter from "@/components/shared/Newsletter"
import Head from "next/head"

const BlogPage = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogBanner/>
      <section className="section-gap">
        <FeaturedBlog/>
        <AllBlogs/>
      </section>
      <Newsletter/>
    </>
  )
}

export default BlogPage