import Address from '@/components/contact/Address';
import ContactUs from '@/components/contact/ContactUs';
import Head from 'next/head'

const Contact = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Address/>
      <ContactUs/>
    </>
  )
}

export default Contact;