import AboutUs from '@/components/home/about/AboutUs';
import Banner from '@/components/home/Banner';
import PopularCategory from '@/components/home/category/PopularCategory';
import Company from '@/components/home/Company';
import JobByLocation from '@/components/home/JobByLocation';
import LatestJob from '@/components/home/latestJob/LatestJob';
import StartWith from '@/components/home/startWith/StartWith';
import Blog from '@/components/shared/blog/Blog';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Job Portal | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <Company/>
      <StartWith/>
      <PopularCategory/>
      <AboutUs/>
      <LatestJob/>
      <JobByLocation/>
      <Blog/>
    </>
  )
}
