import AboutUs from '@/components/home/about/AboutUs';
import Banner from '@/components/home/Banner';
import PopularCategory from '@/components/home/category/PopularCategory';
import Company from '@/components/home/Company';
import JobByLocation from '@/components/home/JobByLocation';
import LatestJob from '@/components/home/latestJob/LatestJob';
import StartWith from '@/components/home/startWith/StartWith';
import Blog from '@/components/shared/blog/Blog';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Job Portal | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;900&display=swap" rel="stylesheet"/>
      </Head>
      
      <Banner/>
      <Company/>
      <StartWith/>
      <PopularCategory/>
      <AboutUs/>
      <LatestJob/>
      <JobByLocation/>
      <Blog/>
    </>
  )
}
