import AllJob from '@/components/job/allJob/AllJob';
import JobBanner from '@/components/job/JobBanner';
import Blog from '@/components/shared/blog/Blog';
import Newsletter from '@/components/shared/Newsletter';
import Head from 'next/head';

const Job = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Find a Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;900&display=swap" rel="stylesheet"/>
      </Head>
      
      <JobBanner/>
      <AllJob/>
      <Blog dataClass="job-blog"/>
      <Newsletter/>
    </>
  )
}

export default Job;