import AllJob from '@/components/job/allJob/AllJob';
import JobBanner from '@/components/job/JobBanner';
import Blog from '@/components/shared/blog/Blog';
import Head from 'next/head';

const job = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobBanner/>
      <AllJob/>
      <Blog dataClass="job-blog"/>
    </>
  )
}

export default job;