import BgSection from "@/components/authentication/BgSection"
import Login from "@/components/authentication/Login"
import Head from "next/head"

const Signin = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
      <BgSection/>
    </>
  )
}

export default Signin