import Faq from "@/components/pricing/Faq";
import FaqContact from "@/components/pricing/FaqContact";
import Price from "@/components/pricing/prices/Price";
import Head from "next/head";

const Pricing = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Price/>
      <Faq/>
      <FaqContact/>
    </>
  )
}

export default Pricing;