import Faq from "@/components/pricing/Faq";
import FaqContact from "@/components/pricing/FaqContact";
import Price from "@/components/pricing/prices/Price";
import Head from "next/head";

const Pricing = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;900&display=swap" rel="stylesheet"/>
      </Head>
      
      <Price/>
      <Faq/>
      <FaqContact/>
    </>
  )
}

export default Pricing;