import { companies } from '@/data/company';
import Head from 'next/head';
import CompanyBanner from '@/components/singleCompany/CompanyBanner';
import CompanyDetails from '@/components/singleCompany/companyDetails/CompanyDetails';
import CompanyLocation from '@/components/singleCompany/CompanyLocation';
import Newsletter from '@/components/shared/Newsletter';

const SingleCompany = ({singleCompany}) => {
  return (
    <>
      <Head>
        <title>Job Portal | Company Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;900&display=swap" rel="stylesheet"/>
      </Head>
      
      <CompanyBanner singleCompany={singleCompany}/>
      <CompanyDetails singleCompany={singleCompany}/>
      <CompanyLocation/>
      <Newsletter/>
    </>
  )
}

export default SingleCompany;

export const getStaticProps = async (context) => {
  const param = context.params.companyId;
  const data = companies.find(({id}) => id === param);

  return{
    props : {
      singleCompany: data
    }
  }
}

export const getStaticPaths = async () => {
  const paths = companies.map((company) => {
    return {
      params: {
        companyId: company.id
      }
    }
  })

  return {paths, fallback: false}
}