import AllCompany from '@/components/recruiters/allCompany/AllCompany';
import RecruiterBanner from '@/components/recruiters/RecruiterBanner';
import Blog from '@/components/shared/blog/Blog';
import Newsletter from '@/components/shared/Newsletter';
import Head from 'next/head';

const Recruiters = () => {
  return (
    <>
      <Head>
        <title>Job Portal | Recruiters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruiterBanner/>
      <AllCompany/>
      <Blog dataClass="job-blog"/>
      <Newsletter/>
    </>
  )
}

export default Recruiters